### ISSUE TITLE
AnimationControllers not disposed properly

### ISSUE THREAD

**Issue by Innovation-Harbour** [TheAlphamerc/empty_widget#3] opened 2021-04-17 15:22 UTC
**Describe the bug**
_EmptyListWidgetState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

**Comment by TheAlphamerc** [comment] 2021-04-18 08:19
Hi @Innovation-Harbour, Can you let me know which version of package you are using ?

**Comment by Innovation-Harbour** [comment] 2021-04-18 14:58
HI, i am using the v0.01.. i see there is a new version now.. i can have that installed

**Comment by TheAlphamerc** [comment] 2021-04-19 04:13
@Innovation-Harbour  the issue is fixed in v0.0.2. Let me know if you still face any issue.

**Closed** 2021-05-12 05:35 UTC
